### ISSUE TITLE
Let handlers decide whether to trust remote spans

### ISSUE THREAD

**Issue by akshayjshah** [bufbuild/connect-opentelemetry-go#47]
With the changes in #41, I think we're currently assuming that handlers are internal: if the client has already created a trace, we add new spans to it. (After the holiday break, everything's a little hazy - I could be wrong about this!)

This is fine for RPCs within a trusted system, but it's not the right approach for external-facing servers. External-facing handlers should instead create a new span and attach any span sent by the client as a link (using [trace.LinkFromContext](https://pkg.go.dev/go.opentelemetry.io/otel/trace#LinkFromContext)). We should look at `otelgrpc` and `otelhttp` to make sure we get this right.

I lean toward making the external API behavior the default, since it's safest, but I'm not sure.

**Comment by joshcarp** [comment]
I'm thinking that something like a `WithUntrustedSpan` option would probably work

**Comment by joshcarp** [comment]
Not tested but something like this might work
```go
opts := []trace.SpanStartOption{
	trace.WithSpanKind(spanKind),
	trace.WithAttributes(attributes...),
}
if i.config.untrusted {
	opts = append(opts,
		trace.WithLinks(trace.LinkFromContext(ctx)),
		trace.WithNewRoot(),
	)
}
ctx, span := i.config.tracer.Start(
	ctx,
	name,
	opts...,
)
```

**Comment by joshcarp** [comment]
Behaviour I am implementing:
- All server spans are untrusted by default, the user can explicitly trust with WithTrustRemote()
- All client spans are trusted by default,  WithTrustRemote()  is a noop

- By default remote spans are untrusted (Newly created spans are not children but are linked)
- If you pass in WithTrustRemote() then all traces entering a handler will be trusted (newly created spans are children of remote spans)
- If you pass in WithTrustRemote() to a client, nothing happens because there are never any “remote” spans passed in to a client
